### ISSUE TITLE
What happens when you hit too many repos at once

### ISSUE THREAD

**Issue by pelson** [pelson/repo-health-report#3]
I was getting pandas, numpy and d3.js all at the same time. They were all fetching stargazer information, which is typically a lot.

```
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/app/.conda/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/app/webapp.py", line 125, in fetch_repo_data
    for stargazer in stargazers]
  File "/app/webapp.py", line 124, in 
    stargazer_data = [{'starred_at': stargazer.raw_data['starred_at'], 'login': stargazer.raw_data['user']['login']}
  File "/app/.conda/lib/python3.5/site-packages/github/PaginatedList.py", line 49, in __iter__
    newElements = self._grow()
  File "/app/.conda/lib/python3.5/site-packages/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/app/.conda/lib/python3.5/site-packages/github/PaginatedList.py", line 162, in _fetchNextPage
    headers=self.__headers
  File "/app/.conda/lib/python3.5/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/app/.conda/lib/python3.5/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {'message': 'You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.', 'documentation_url': 'https://developer.github.com/v3/#abuse-rate-limits'}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/webapp.py", line 204, in get
    payload = datastore[uuid].result()
  File "/app/.conda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/app/.conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
github.GithubException.GithubException: 403 {'message': 'You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.', 'documentation_url': 'https://developer.github.com/v3/#abuse-rate-limits'}

403 {'message': 'You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.', 'documentation_url': 'https://developer.github.com/v3/#abuse-rate-limits'}
```

**Comment by pelson** [comment]
Nothing to be done here, just wanted to record the problem.

**Comment by pelson** [comment]
(the error given is pretty good)
